language: csharp
solution: Konvenience.sln
install:
  - nuget restore Konvenience.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Konvenience.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./KonvenienceTests/bin/Release/KonvenienceTests.dll
